Hw03
Rinya7/Nodejs-rest-api-hw02-express pull request #2
Opened 2023-09-13 12:34 UTC by Rinya7

to check

2023-09-13 18:07 UTC, KhYulian commented on constants/env.js
> +}
особисто ніколи не стикався з таким підходом на проектах. Зазвичай side-effects при імпортах вважаються поганою практикою ( коли файл, який ви імпортуєте відразу виконує якийсь код, викликає функції чи кидає помилки)

2023-09-13 18:07 UTC, KhYulian commented on constants/env.js
> +}
помилка в терміналі впаде сама по собі, якщо якась змінна відсутня, тому краще видаліть цей файл

2023-09-13 18:09 UTC, KhYulian requested changes
Чудова робота, лиш виправте про що я написав

2023-09-14 07:04 UTC, Rinya7 commented
исправил

2023-09-18 11:13 UTC, merged